In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv(r"C:\Users\parth\Downloads\Titanic (1).csv")
df.head()

,Name,PClass,Age,Sex,Survived
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1
1,"Allison, Miss Helen Loraine",1st,2.00,female,0
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0
4,"Allison, Master Hudson Trevor",1st,0.92,male,1

In [4]:
df.shape

(1313, 5)

In [5]:
df.describe

<bound method NDFrame.describe of                                                Name PClass    Age     Sex  \
0                      Allen, Miss Elisabeth Walton    1st  29.00  female
1                       Allison, Miss Helen Loraine    1st   2.00  female
2               Allison, Mr Hudson Joshua Creighton    1st  30.00    male
3     Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female
4                     Allison, Master Hudson Trevor    1st   0.92    male
...                                             ...    ...    ...     ...
1308                             Zakarian, Mr Artun    3rd  27.00    male
1309                         Zakarian, Mr Maprieder    3rd  26.00    male
1310                               Zenni, Mr Philip    3rd  22.00    male
1311                               Lievens, Mr Rene    3rd  24.00    male
1312                                 Zimmerman, Leo    3rd  29.00    male

      Survived
0            1
1            0
2            0
3            0
4            1
...        ...
1308         0
1309         0
1310         0
1311         0
1312         0

[1313 rows x 5 columns]>

In [6]:
df.isna().sum()

Name          0
PClass        1
Age         557
Sex           0
Survived      0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1313 entries, 0 to 1312
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      1313 non-null   object
 1   PClass    1312 non-null   object
 2   Age       756 non-null    float64
 3   Sex       1313 non-null   object
 4   Survived  1313 non-null   int64
dtypes: float64(1), int64(1), object(3)
memory usage: 51.4+ KB

In [9]:
df['Age'].fillna(df['Age'].median(),inplace=True)

C:\Users\parth\AppData\Local\Temp\ipykernel_4840\1527141296.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(),inplace=True)

In [13]:
df['PClass'].fillna(df['PClass'].mode()[0],inplace=True)

In [14]:
df.isna().sum()

Name        0
PClass      0
Age         0
Sex         0
Survived    0
dtype: int64

In [20]:
df['Sex']=df['Sex'].map({'male':0,'female':1})

In [21]:
df['Sex'].unique()

array([1, 0])

In [22]:
df.head()

                                            Name PClass    Age  Sex  Survived
0                   Allen, Miss Elisabeth Walton    1st  29.00    1         1
1                    Allison, Miss Helen Loraine    1st   2.00    1         0
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    0         0
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00    1         0
4                  Allison, Master Hudson Trevor    1st   0.92    0         1